- name: Remove nginx on RedHat systems
  yum: name=nginx state=absent
  when: ansible_distribution == "RedHat"
  tags: [ never, remove ]

- name: Remove nginx on Ubuntu systems
  apt: name=nginx-common state=absent
  when: ansible_distribution == "Ubuntu"
  tags: [ never, remove ]

